#!/usr/bin/env python

import os
import argparse
import tomllib

import logging

import sys
import re

import pathlib

import colorama as C

import shutil
import subprocess

import glob

import hashlib

import datetime

safe_dir_re = re.compile("^[a-zA-Z0-9._-]+$")
triple_quotes_re = re.compile("'''")

logging.basicConfig(
    format="[{levelname}] {message}",
    style="{",
)

BASE_DIR=os.getcwd()

def sha256sum(filename):
    with open(filename, 'rb', buffering=0) as f:
        return hashlib.file_digest(f, 'sha256').hexdigest()

def print_parameters(params_dict):
    print("Key parameters:")
    print(f" >       N_micro = {params_dict["N_micro"]}")
    print(f" >         N_mfl = {params_dict["N_mfl"]}")
    print(f" >      max_iter = {params_dict["max_iter"]}")
    print(f" >            δt = {params_dict["δt"]}")
    print(f" > n_communities = {params_dict["init_lfr_target_n_communities"]}")
    print(f" >             µ = {params_dict["init_lfr_kwargs"]["mixing_parameter"]}")
    print(f" >          β_σ² = {params_dict["init_lfr_kwargs"]["β_σ²"]}")

def load_parameters(dir_name):
    params_filename = os.path.join(dir_name, "params.toml")
    if not os.path.isfile(params_filename):
        logging.warning(f"parameter file ({params_filename}) not found!")
        return None
    else:
        logging.debug("loading parameters")
        with open(params_filename, "rb") as params_f:
            return tomllib.load(params_f)

def find_info_filename(args, name):
    dest_dir = os.path.abspath(args.save_base_dir)
    globbed_dir = glob_run(dest_dir, name)
    if globbed_dir:
        target_dir = globbed_dir
    else:
        target_dir = os.path.join(dest_dir, name)
    info_filename = os.path.join(target_dir, "info.toml")
    if os.path.isfile(info_filename):
        return {"filename":info_filename, "prefix":target_dir}
    else:
        return None

def load_info(args, name):
    info_filename = find_info_filename(args, name)
    if info_filename is not None:
        with open(info_filename["filename"], "rb") as info_f:
            return {"dict":tomllib.load(info_f), "prefix":info_filename["prefix"]}
    else:
        logging.error(f"no run found with name {name}")
        sys.exit(1)

def describe_run(args, name, parameters=False):
    info = load_info(args, name)
    if info is not None:
        if args.one_line:
            print(name)
        else:
            info_dict = info["dict"]
            saved_size = round(info_dict["size"] / 1024 / 1024)
            print(f"{C.Fore.YELLOW}{C.Style.BRIGHT}{name}{C.Style.NORMAL}{C.Fore.RESET} ({saved_size} MB)")
            print(f"  ran: {info_dict.get("run_date", "-")}")
            print(f"saved: {info_dict.get("save_date", "-")}")
            mfl_data_sha = info_dict.get("mfl_data_sha256", "-")
            print(f"{C.Fore.BLUE}{mfl_data_sha}{C.Fore.RESET}")
            if "description" in info_dict:
                print(f"  {C.Style.DIM}{info_dict["description"].replace("\n", "\n  ")}{C.Style.NORMAL}")
            if parameters:
                print(f"          N_micro = {info_dict["parameters"]["N_micro"]}")
                print(f"            N_mfl = {info_dict["parameters"]["N_mfl"]}")
                print(f"         max_iter = {info_dict["parameters"]["max_iter"]}")
                print(f"               δt = {info_dict["parameters"]["delta_t"]:.2e}")
                print(f"    n_communities = {info_dict["parameters"]["n_communities"]}")
                print(f"                µ = {info_dict["parameters"]["mu"]}")
                print(f"             β_σ² = {info_dict["parameters"]["beta_sigma_squared"]}")
            print()

def check_toml_valid(path):
    with open(path, "rb") as f:
        try:
            tomllib.load(f)
        except:
            return False
        return True

def glob_run(dest_dir, name):
    globbed_dirs = glob.glob(f"{dest_dir}/{name}*")
    if len(globbed_dirs) == 1:
        return globbed_dirs[0]
    else:
        return False


def list_runs(args):
    dest_dir = os.path.abspath(args.save_base_dir)
    found = 0
    for d in os.listdir(dest_dir):
        info_filename = os.path.join(dest_dir, d, "info.toml")
        logging.debug(f"probing {info_filename}")
        if os.path.isfile(info_filename):
            found += 1
            describe_run(args, d, parameters=args.parameters)
    if found == 0:
        print("no run found")

def move_run(args):
    dest_dir = os.path.abspath(args.save_base_dir)
    source_dir = os.path.join(dest_dir, args.old_name)
    destination_dir = os.path.join(dest_dir, args.new_name)
    if os.path.isfile(os.path.join(source_dir, "info.toml")):
        if os.path.exists(destination_dir):
            logging.error("new name already taken")
            sys.exit(1)
        shutil.move(source_dir, destination_dir)
    else:
        logging.error("unknown run name")
        sys.exit(1)

def remove_run(args):
    dest_dir = os.path.abspath(args.save_base_dir)
    target_dir = os.path.join(dest_dir, args.target_run)
    if os.path.isfile(os.path.join(target_dir, "info.toml")):
        ans = input(f"remove run {args.target_run}? [y/N]")
        if ans != 'y':
            return
        shutil.rmtree(target_dir)
    else:
        logging.error("unknown run name")
        sys.exit(1)

def play_run(args):
    info = load_info(args, args.target_run)
    info_dict = info["dict"]
    mfl_dir = info_dict["paths"]["mfl_dir"]
    movie_filename = os.path.join(info["prefix"], mfl_dir, "movie.mp4")
    subprocess.run(["vlc", movie_filename])

def edit_run(args):
    dest_dir = os.path.abspath(args.save_base_dir)
    globbed_dir = glob_run(dest_dir, args.target_run)
    if globbed_dir:
        target_dir = globbed_dir
    else:
        target_dir = os.path.join(dest_dir, args.target_run)
    info_filename = os.path.join(target_dir, "info.toml")
    if os.path.isfile(info_filename):
        temp_filename = f"{info_filename}.temp"
        shutil.copy(info_filename, temp_filename)
        editor = os.environ.get("editor", "vi")
        subprocess.run([editor, temp_filename])
        stats = os.stat(temp_filename)
        if stats.st_mtime == stats.st_ctime:
            # file was not modified since it was created, aborting
            logging.info("run info file left unmodified")
            os.remove(temp_filename)
        elif check_toml_valid(temp_filename):
            logging.info("run info file updated")
            shutil.move(temp_filename, info_filename)
        else:
            logging.error("new file has invalid syntax, aborting")
            os.remove(temp_filename)
            sys.exit(1)
    else:
        logging.error("unknown run name")
        sys.exit(1)

def save(args):
    dest_dir = os.path.abspath(args.save_base_dir)

    for mfl_dir in args.dirnames:

        got_mfl = False
        got_micro = False
        got_ref = False

        mfl_dir_abs = os.path.abspath(mfl_dir)
        logging.info(f"processing {mfl_dir}")

        logging.debug("looking for MFL parameter file...")
        params_filename = os.path.join(mfl_dir_abs, "params.toml")
        if not os.path.isfile(params_filename):
            logging.error(f"MFL parameter file ({params_filename}) not found!")
            sys.exit(1)
        else:
            got_mfl = True

        logging.debug("copying MFL dir")
        shutil

        logging.debug("loading MFL parameters")
        with open(params_filename, "rb") as params_f:
            mfl_params_dict = tomllib.load(params_f)

        micro_data_file = mfl_params_dict.get("init_micro_filename", None)
        if micro_data_file is None:
            logging.warning("micro run data file not found!")
        else:
            micro_dir = os.path.dirname(micro_data_file)
            micro_dir_abs = os.path.abspath(micro_dir)
            logging.info(f"found micro dir @ {micro_dir}")

            micro_params_filename = os.path.join(micro_dir, "params.toml")
            if not os.path.isfile(micro_params_filename):
                logging.warning(f"parameter file ({micro_params_filename}) not found!")
            else:
                logging.debug("loading micro parameters")
                with open(micro_params_filename, "rb") as micro_params_f:
                    micro_params_dict = tomllib.load(micro_params_f)

                got_micro = True

                ref_data_file = micro_params_dict.get("init_micro_filename", None)
                if ref_data_file is None:
                    logging.warning("reference data file not found!")
                else:
                    ref_dir = os.path.dirname(ref_data_file)
                    ref_dir_abs = os.path.abspath(ref_dir)
                    logging.info(f"found ref dir @ {ref_dir}")

                    got_ref = True

        print_parameters(mfl_params_dict)

        short_name = ""
        while not safe_dir_re.match(short_name):
            short_name = input("Short name: ")
            dest_prefix = os.path.join(dest_dir, short_name)
            if os.path.isdir(dest_prefix):
                logging.error("this name is already taken, choose another")
                short_name = ""


        description = ""
        description_valid = False
        while not description_valid:
            print("description (finish with Ctrl+D): ")
            description = sys.stdin.read().strip()
            if triple_quotes_re.search(description):
                logging.error("triple quotes are not allowed in the description")
                continue
            description_valid = True

        # create destination dir (got_mfl is True at this point)
        pathlib.Path(dest_dir).mkdir(parents=True, exist_ok=True)

        if got_mfl: # actually not needed
            mfl_dest_full_dir = os.path.join(dest_prefix, mfl_dir_abs.removeprefix(os.path.join(os.getcwd(), "results/")))
            logging.info(f"copying mfl data to {mfl_dest_full_dir}")
            shutil.copytree(mfl_dir, mfl_dest_full_dir)

        if got_micro:
            micro_dest_full_dir = os.path.join(dest_prefix, micro_dir_abs.removeprefix(os.path.join(os.getcwd(), "results/")))
            logging.info(f"copying micro data to {micro_dest_full_dir}")
            shutil.copytree(micro_dir, micro_dest_full_dir)

        if got_ref:
            ref_dest_full_dir = os.path.join(dest_prefix, ref_dir_abs.removeprefix(os.path.join(os.getcwd(), "results/")))
            logging.info(f"copying ref data to {ref_dest_full_dir}")
            shutil.copytree(ref_dir, ref_dest_full_dir)

        saved_size = sum(f.stat().st_size for f in pathlib.Path(dest_prefix).glob('**/*') if f.is_file())

        mfl_data_sha = sha256sum(os.path.join(mfl_dir_abs, "data.hdf5"))

        save_date = datetime.datetime.now().strftime('%a %d %b %H:%M:%S %Y')

        stat = os.stat(os.path.join(mfl_dir_abs, "data.hdf5"))
        run_date = datetime.datetime.fromtimestamp(stat.st_mtime).strftime('%a %d %b %H:%M:%S %Y')

        # create a TOML file to synthesize this run
        info_filename = os.path.join(dest_prefix, "info.toml")
        logging.info(f"creating info file @ {info_filename}")
        with open(info_filename, "w") as info_f:
            info_f.write(f"short_name = '{short_name}'\n")
            if len(description) > 0:
                info_f.write("description = '''\n")
                info_f.write(f"{description}'''\n")
            info_f.write(f"size = {saved_size}\n")
            info_f.write(f"mfl_data_sha256 = '{mfl_data_sha}'\n")
            info_f.write(f"save_date = '{save_date}'\n")
            info_f.write(f"run_date = '{run_date}'\n")

            info_f.write("[parameters]\n")
            info_f.write(f"N_micro = {mfl_params_dict["N_micro"]}\n")
            info_f.write(f"N_mfl = {mfl_params_dict["N_mfl"]}\n")
            info_f.write(f"max_iter = {mfl_params_dict["max_iter"]}\n")
            info_f.write(f"delta_t = {mfl_params_dict["δt"]}\n")
            info_f.write(f"n_communities = {mfl_params_dict["init_lfr_target_n_communities"]}\n")
            info_f.write(f"mu = {mfl_params_dict["init_lfr_kwargs"]["mixing_parameter"]}\n")
            info_f.write(f"beta_sigma_squared = {mfl_params_dict["init_lfr_kwargs"]["β_σ²"]}\n")

            info_f.write("[paths]\n")
            info_f.write(f"mfl_dir = \"{mfl_dir.removeprefix("results/")}\"\n")
            if got_micro:
                info_f.write(f"micro_dir = \"{micro_dir.removeprefix("results/")}\"\n")
            if got_ref:
                info_f.write(f"ref_dir = \"{ref_dir.removeprefix("results/")}\"\n")

            # git_commit_id = subprocess.run(["git", "-C", "dev/OpiForm", "rev-parse", "HEAD"], capture_output = True, text=True).stdout.strip()
            # info_f.write("[git]\n")
            # info_f.write(f"commit_id = {git_commit_id}")





def main():

    parser = argparse.ArgumentParser(
                    prog='manage',
                    description='manage OpiForm simulation results')

    parser.add_argument('-v', '--verbose', action='store_true')
 
    subparsers = parser.add_subparsers(help='command', required=True)

    save_parser = subparsers.add_parser('save', aliases=['s'], help='save MFL run along with reference and micro run, with a description')
    save_parser.set_defaults(func=save)

    save_parser.add_argument('dirnames', nargs='+')
    save_parser.add_argument('-d', '--save-base-dir', type=str, default="saved_results")

    list_parser = subparsers.add_parser('list', aliases=['l'], help='list MFL runs')
    list_parser.set_defaults(func=list_runs)

    list_parser.add_argument('-1', '--one-line', action="store_true")
    list_parser.add_argument('-p', '--parameters', action="store_true")
    list_parser.add_argument('-d', '--save-base-dir', type=str, default="saved_results")

    move_parser = subparsers.add_parser('move', aliases=['m'], help='move MFL run')
    move_parser.set_defaults(func=move_run)

    move_parser.add_argument('-d', '--save-base-dir', type=str, default="saved_results")
    move_parser.add_argument('old_name')
    move_parser.add_argument('new_name')

    remove_parser = subparsers.add_parser('remove', aliases=['r'], help='remove MFL run')
    remove_parser.set_defaults(func=remove_run)

    remove_parser.add_argument('-d', '--save-base-dir', type=str, default="saved_results")
    remove_parser.add_argument('target_run')

    edit_parser = subparsers.add_parser('edit', aliases=['e'], help='edit MFL run')
    edit_parser.set_defaults(func=edit_run)

    edit_parser.add_argument('-d', '--save-base-dir', type=str, default="saved_results")
    edit_parser.add_argument('target_run')

    play_parser = subparsers.add_parser('play', aliases=['p'], help='play MFL run')
    play_parser.set_defaults(func=play_run)

    play_parser.add_argument('-d', '--save-base-dir', type=str, default="saved_results")
    play_parser.add_argument('target_run')

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    else:
        logging.getLogger().setLevel(logging.INFO)

    args.func(args)

main()
